/**
 * Calendario de temporada de fruta y verdura en ESPAÑA (datos estructurados).
 *
 * Fuente de VERDAD para la temporalidad: la IA lee ESTO, nunca lo inventa.
 * Calendario orientativo del mercado español (producción nacional + huerta).
 * Los meses van de 1 (enero) a 12 (diciembre); un rango [10,5] cruza fin de año.
 */
import type { ProductSeasonData } from './types';

export const SEASON_DATA: ProductSeasonData[] = [
  // ── Frutas ────────────────────────────────────────────────
  { key: 'naranja', category: 'Frutas', mainMonths: [10, 5], origin: 'Valencia, Andalucía', national: true, availability: 'alta', notes: 'Frutal de invierno; la navel y la sanguina son las más comunes.' },
  { key: 'mandarina', category: 'Frutas', mainMonths: [10, 3], origin: 'Valencia, Castellón', national: true, availability: 'alta' },
  { key: 'clementina', category: 'Frutas', mainMonths: [10, 2], origin: 'Castellón, Sevilla', national: true, availability: 'alta' },
  { key: 'limón', category: 'Frutas', mainMonths: [11, 5], origin: 'Murcia, Alicante', national: true, availability: 'alta' },
  { key: 'plátano', category: 'Frutas', mainMonths: [1, 12], origin: 'Canarias', national: true, availability: 'alta', notes: 'Disponible todo el año por producción canaria.' },
  { key: 'fresa', category: 'Frutas', mainMonths: [2, 5], origin: 'Huelva', national: true, availability: 'alta', notes: 'Fresón de Huelva en plena campaña de febrero a mayo.' },
  { key: 'fresón', category: 'Frutas', mainMonths: [2, 5], origin: 'Huelva', national: true, availability: 'alta' },
  { key: 'níspero', category: 'Frutas', mainMonths: [4, 5], origin: 'Callosa d’en Sarrià (Alicante)', national: true, availability: 'media' },
  { key: 'albaricoque', category: 'Frutas', mainMonths: [5, 8], origin: 'Murcia, Valencia', national: true, availability: 'media' },
  { key: 'cereza', category: 'Frutas', mainMonths: [5, 7], origin: 'Valle del Jerte (Extremadura)', national: true, availability: 'media' },
  { key: 'melocotón', category: 'Frutas', mainMonths: [5, 9], origin: 'Murcia, Lleida', national: true, availability: 'alta' },
  { key: 'nectarina', category: 'Frutas', mainMonths: [5, 9], origin: 'Murcia, Lleida', national: true, availability: 'alta' },
  { key: 'sandía', category: 'Frutas', mainMonths: [6, 8], origin: 'Cuenca, Ciudad Real, Almería', national: true, availability: 'alta' },
  { key: 'melón', category: 'Frutas', mainMonths: [6, 9], origin: 'Cuenca, Manzanares', national: true, availability: 'alta' },
  { key: 'higo', category: 'Frutas', mainMonths: [7, 9], origin: 'Extremadura, Cataluña', national: true, availability: 'media' },
  { key: 'ciruela', category: 'Frutas', mainMonths: [6, 9], origin: 'Murcia, Valencia', national: true, availability: 'media' },
  { key: 'uva', category: 'Frutas', mainMonths: [9, 12], origin: 'Murcia, Vinalopó', national: true, availability: 'alta', notes: 'Uva de mesa nacional de otoño.' },
  { key: 'manzana', category: 'Frutas', mainMonths: [9, 12], origin: 'Lleida, Girona, Asturias', national: true, availability: 'alta', notes: 'También disponible en conservación.' },
  { key: 'pera', category: 'Frutas', mainMonths: [7, 11], origin: 'Lleida, Ribera del Duero', national: true, availability: 'alta' },
  { key: 'caqui', category: 'Frutas', mainMonths: [10, 1], origin: 'Ribera del Xúquer', national: true, availability: 'media' },
  { key: 'persimón', category: 'Frutas', mainMonths: [10, 1], origin: 'Ribera del Xúquer', national: true, availability: 'media' },
  { key: 'chirimoya', category: 'Frutas', mainMonths: [10, 1], origin: 'Costa Tropical de Granada', national: true, availability: 'media' },
  { key: 'granada', category: 'Frutas', mainMonths: [9, 11], origin: 'Murcia, Alicante', national: true, availability: 'media' },
  { key: 'kiwi', category: 'Frutas', mainMonths: [10, 3], origin: 'Galicia, Asturias', national: true, availability: 'media' },
  { key: 'aguacate', category: 'Frutas', mainMonths: [11, 5], origin: 'Costa Tropical de Granada, Málaga', national: true, availability: 'baja' },
  { key: 'mango', category: 'Frutas', mainMonths: [7, 10], origin: 'Málaga, Granada', national: true, availability: 'baja' },
  { key: 'piña', category: 'Frutas', mainMonths: [1, 12], origin: 'Importada (Costa Rica)', imported: true, availability: 'alta' },
  { key: 'papaya', category: 'Frutas', mainMonths: [1, 12], origin: 'Importada / Canarias', imported: true, availability: 'media' },
  { key: 'arándano', category: 'Frutas', mainMonths: [5, 7], origin: 'Huelva, Asturias', national: true, availability: 'media' },
  { key: 'frambuesa', category: 'Frutas', mainMonths: [5, 8], origin: 'Huelva, Asturias', national: true, availability: 'media' },
  { key: 'coco', category: 'Frutas', mainMonths: [1, 12], imported: true, availability: 'baja' },
  { key: 'melocotón de calanda', category: 'Frutas', mainMonths: [7, 10], origin: 'Bajo Aragón', national: true, availability: 'media' },

  // ── Verduras ──────────────────────────────────────────────
  { key: 'tomate', category: 'Verduras', mainMonths: [4, 10], secondaryMonths: [12, 3], origin: 'Almería, Murcia, Canarias', national: true, availability: 'alta', notes: 'Casi todo el año por invernadero (Almería); plena campaña de mayo a septiembre.' },
  { key: 'tomate cherry', category: 'Verduras', mainMonths: [5, 10], origin: 'Almería, Granada', national: true, availability: 'alta' },
  { key: 'patata', category: 'Verduras', mainMonths: [5, 8], secondaryMonths: [9, 12], origin: 'Castilla y León, Galicia, Murcia', national: true, availability: 'alta', notes: 'Producto básico, disponible todo el año (conservación).' },
  { key: 'cebolla', category: 'Verduras', mainMonths: [4, 7], origin: 'La Mancha, Lleida', national: true, availability: 'alta', notes: 'Disponible todo el año.' },
  { key: 'cebolla dulce', category: 'Verduras', mainMonths: [4, 6], origin: 'Figueres, Reus', national: true, availability: 'media' },
  { key: 'zanahoria', category: 'Verduras', mainMonths: [1, 12], origin: 'Navarra, Aragón, Granada', national: true, availability: 'alta', notes: 'Calidad y disponibilidad todo el año.' },
  { key: 'pimiento', category: 'Verduras', mainMonths: [5, 10], origin: 'Murcia, Almería, Gredos', national: true, availability: 'alta' },
  { key: 'pimiento italiano', category: 'Verduras', mainMonths: [6, 10], origin: 'Murcia, Almería', national: true, availability: 'media' },
  { key: 'berenjena', category: 'Verduras', mainMonths: [5, 10], origin: 'Murcia, Almería', national: true, availability: 'media' },
  { key: 'calabacín', category: 'Verduras', mainMonths: [4, 10], origin: 'Almería, Murcia', national: true, availability: 'alta' },
  { key: 'pepino', category: 'Verduras', mainMonths: [4, 9], origin: 'Almería, Granada', national: true, availability: 'alta' },
  { key: 'calabaza', category: 'Verduras', mainMonths: [9, 12], origin: 'Valencia, Toledo', national: true, availability: 'media' },
  { key: 'espinaca', category: 'Verduras', mainMonths: [9, 5], origin: 'La Rioja, Valencia', national: true, availability: 'media' },
  { key: 'acelga', category: 'Verduras', mainMonths: [10, 4], origin: 'Valencia, Murcia', national: true, availability: 'media' },
  { key: 'coliflor', category: 'Verduras', mainMonths: [10, 4], origin: 'Murcia, Alicante', national: true, availability: 'media' },
  { key: 'brócoli', category: 'Verduras', mainMonths: [10, 4], origin: 'Murcia, Alicante', national: true, availability: 'media' },
  { key: 'col', category: 'Verduras', mainMonths: [10, 4], origin: 'Valencia, Murcia', national: true, availability: 'media' },
  { key: 'repollo', category: 'Verduras', mainMonths: [10, 4], origin: 'Valencia, Murcia', national: true, availability: 'media' },
  { key: 'judía verde', category: 'Verduras', mainMonths: [5, 9], origin: 'Navarra, Andalucía', national: true, availability: 'media' },
  { key: 'guisante', category: 'Verduras', mainMonths: [3, 5], origin: 'Navarra, La Rioja', national: true, availability: 'baja' },
  { key: 'habas', category: 'Verduras', mainMonths: [3, 5], origin: 'Andalucía', national: true, availability: 'baja' },
  { key: 'alcachofa', category: 'Verduras', mainMonths: [11, 4], origin: 'Murcia, Alicante, Vega Baja', national: true, availability: 'media' },
  { key: 'espárrago', category: 'Verduras', mainMonths: [3, 6], origin: 'Navarra', national: true, availability: 'baja' },
  { key: 'puerro', category: 'Verduras', mainMonths: [9, 4], origin: 'Lleida, Valencia', national: true, availability: 'media' },
  { key: 'remolacha', category: 'Verduras', mainMonths: [5, 10], origin: 'Valladolid, Burgos', national: true, availability: 'media' },
  { key: 'apio', category: 'Verduras', mainMonths: [10, 5], origin: 'Murcia, Sevilla', national: true, availability: 'media' },
  { key: 'maíz', category: 'Verduras', mainMonths: [6, 9], origin: 'Galicia, Navarra', national: true, availability: 'media' },
  { key: 'champiñón', category: 'Verduras', mainMonths: [1, 12], origin: 'La Rioja', national: true, availability: 'alta', notes: 'Cultivo en interior, disponible todo el año.' },
  { key: 'setas', category: 'Verduras', mainMonths: [9, 12], origin: 'Castilla-La Mancha', national: true, availability: 'baja' },
  { key: 'pimiento de piquillo', category: 'Verduras', mainMonths: [6, 10], origin: 'Navarra', national: true, availability: 'media' },
  { key: 'boniato', category: 'Verduras', mainMonths: [9, 12], origin: 'Málaga, Valencia', national: true, availability: 'baja' },
  { key: 'calabacín', category: 'Verduras', mainMonths: [4, 10], origin: 'Almería, Murcia', national: true, availability: 'alta' },

  // ── Ensaladas ─────────────────────────────────────────────
  { key: 'lechuga', category: 'Ensaladas', mainMonths: [1, 12], origin: 'Levante, huerta murciana', national: true, availability: 'alta', notes: 'Producción todo el año, con picos de primavera-verano.' },
  { key: 'lechuga romana', category: 'Ensaladas', mainMonths: [1, 12], origin: 'Murcia, Almería', national: true, availability: 'alta' },
  { key: 'iceberg', category: 'Ensaladas', mainMonths: [1, 12], origin: 'Murcia, Almería', national: true, availability: 'alta' },
  { key: 'cogollos', category: 'Ensaladas', mainMonths: [1, 12], origin: 'Murcia, Almería', national: true, availability: 'alta' },
  { key: 'canónigos', category: 'Ensaladas', mainMonths: [10, 4], origin: 'Valencia, Murcia', national: true, availability: 'media' },
  { key: 'rúcula', category: 'Ensaladas', mainMonths: [4, 10], origin: 'Murcia, Valencia', national: true, availability: 'media' },
  { key: 'escarola', category: 'Ensaladas', mainMonths: [10, 3], origin: 'Murcia, Valenciana', national: true, availability: 'media' },
  { key: 'endivia', category: 'Ensaladas', mainMonths: [11, 3], origin: 'Cultivo en interior', national: true, availability: 'media' },
  { key: 'brotes', category: 'Ensaladas', mainMonths: [1, 12], origin: 'Huerta levante', national: true, availability: 'media' },
  { key: 'variada', category: 'Ensaladas', mainMonths: [1, 12], origin: 'Huerta levante', national: true, availability: 'media', notes: 'Mix de hojas tiernas, producción continua.' },
  { key: 'espinaca baby', category: 'Ensaladas', mainMonths: [9, 5], origin: 'Valencia, Murcia', national: true, availability: 'media' },
  { key: 'tomate ensalada', category: 'Ensaladas', mainMonths: [4, 10], origin: 'Almería, Murcia', national: true, availability: 'alta' },
];
